module.exports = {
  projects: [
    '<rootDir>/libs/shared/types/rocket',
    '<rootDir>/libs/shared/types/common',
    '<rootDir>/libs/shared/types/launch',
    '<rootDir>/libs/rocket/data/data-rocket',
    '<rootDir>/libs/launch/data/data-launch',
    '<rootDir>/libs/shared/data/data-common',
    '<rootDir>/libs/shared/util/util-ts',
    '<rootDir>/apps/web/launch-timeline',
    '<rootDir>/libs/launch-timeline/features/lazy/launch-timeline',
    '<rootDir>/libs/launch-timeline/ui/launch-overview-card',
    '<rootDir>/libs/shared/util/util-data',
    '<rootDir>/libs/shared/data/data-route-history',
    '<rootDir>/libs/shared/ui/ui-table-of-contents',
    '<rootDir>/libs/shared/stylesheets',
    '<rootDir>/libs/shared/util/util-intersection-observer',
    '<rootDir>/apps/web/rockets',
    '<rootDir>/libs/rockets/features/lazy/rockets-overview',
    '<rootDir>/libs/rocket/ui/ui-rocket-card',
    '<rootDir>/libs/shared/features/shell',
    '<rootDir>/libs/rockets/features/lazy/rocket-detail',
    '<rootDir>/libs/shared/ui/ui-image-slider',
    '<rootDir>/libs/rocket/ui/ui-rocket-engine-card',
  ],
};
